# Generated by Django 3.0.3 on 2022-08-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mayal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombreCat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='nombreSub',
            field=models.CharField(max_length=100),
        ),
    ]
