# Generated by Django 3.2.4 on 2022-08-31 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mayal', '0002_auto_20220831_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='foto',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Galeria'),
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='Galeria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mayal.producto')),
            ],
        ),
    ]
