# Generated by Django 3.2.4 on 2022-08-31 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mayal', '0003_auto_20220831_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='existencias',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Mayal.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='coleccion',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
