# Generated by Django 3.2.4 on 2022-09-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mayal', '0004_auto_20220831_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=1, upload_to='Galeria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='existencias',
            field=models.IntegerField(null=True),
        ),
    ]
