# Generated by Django 3.2.4 on 2022-09-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mayal', '0005_auto_20220902_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='coleccion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='existencias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='material',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
