# Generated by Django 3.0.3 on 2022-10-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mayal', '0007_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
