# Generated by Django 3.0.3 on 2022-10-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mayal', '0010_orderpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(default='Order from mystore', max_length=128),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default='199.99', max_digits=8),
        ),
        migrations.DeleteModel(
            name='OrderPayment',
        ),
    ]
